// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkebnghhbgptfswoihcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZWJuZ2hoYmdwdGZzd29paGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MDgyOTYsImV4cCI6MjA5ODM4NDI5Nn0.sAeMtPa4kUBlq5_ZqetmaBe9sN7SSR44zd9YE8S-_z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});