// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lkebnghhbgptfswoihcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZWJuZ2hoYmdwdGZzd29paGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MDgyOTYsImV4cCI6MjA5ODM4NDI5Nn0.sAeMtPa4kUBlq5_ZqetmaBe9sN7SSR44zd9YE8S-_z8";

// Native website database client (bootcamps, programmes, corporate_clients, mpesa)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Chained LMS Admin database client (academy_applications, instructor_applications, agreements)
const ACADEMY_SUPABASE_URL = "https://xsuktootskxsanncmbtd.supabase.co";
const ACADEMY_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdWt0b290c2t4c2FubmNtYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4Nzg3MTgsImV4cCI6MjA5NjQ1NDcxOH0.DoMXLGWnew1QZxRNpjTX2BlhKRkqWpp4Ij3_LaltL20";

export const academySupabase = createClient(ACADEMY_SUPABASE_URL, ACADEMY_SUPABASE_KEY);